INSERT INTO companies VALUES(1,"BITDEFENDER","bitdefender","salam","$2a$08$e9J5Go8Fki4BCHeIoUx/f.71eyBcS0Res9CrSC5iAIvAKnymWMxhe");
INSERT INTO companies VALUES(2,"INTEL","intel","salam","$2a$10$fwKrYq0pjLAWDVLwyL65Re/aMZVL1K.lIFMRAOCZpK8nhiyGAX4P6");
INSERT INTO companies VALUES(3,"Politehnica","politehnica","salam","$2a$08$e9J5Go8Fki4BCHeIoUx/f.71eyBcS0Res9CrSC5iAIvAKnymWMxhe");
INSERT INTO companies VALUES(4,"FACEBOOK","facebook","salam","$2a$08$e9J5Go8Fki4BCHeIoUx/f.71eyBcS0Res9CrSC5iAIvAKnymWMxhe");
INSERT INTO companies VALUES(5,"ggg","facebook","salam","$2a$08$e9J5Go8Fki4BCHeIoUx/f.71eyBcS0Res9CrSC5iAIvAKnymWMxhe");

INSERT INTO students VALUES(1,"sichitiumarian","sichitiu marian","UNIBUC","$2a$10$fwKrYq0pjLAWDVLwyL65Re/aMZVL1K.lIFMRAOCZpK8nhiyGAX4P6");
INSERT INTO students VALUES(2,"johndoe","johndoe","Facultatea de Moase","$2a$10$fwKrYq0pjLAWDVLwyL65Re/aMZVL1K.lIFMRAOCZpK8nhiyGAX4P6");
INSERT INTO students VALUES(3,"alex","johndoe","Facultatea de Moase","$2a$08$Nk2OhSkPV7AJoTemxTAVYuAg6KJk0BzKGT4tQvMSunJh6X2x5GdCe");

INSERT INTO skills VALUES(1,"phyton",1);
INSERT INTO skills VALUES(2,"C/C++",1);

INSERT INTO skills VALUES(3,"pascal",2);
INSERT INTO skills VALUES(4,"phyton",2);


INSERT INTO jobs VALUES(1,"Software Enginner","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",2);
INSERT INTO jobs VALUES(2,"Programmer","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",2);
INSERT INTO jobs VALUES(3,"HR","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",2);

INSERT INTO jobs VALUES(4,"Software Enginner","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",2);
INSERT INTO jobs VALUES(5,"Programmer","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",2);
INSERT INTO jobs VALUES(6,"HR","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",2);
INSERT INTO jobs VALUES(7,"Software Enginner","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",1);
INSERT INTO jobs VALUES(8,"Programmer","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",1);
INSERT INTO jobs VALUES(9,"HR","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",1);
INSERT INTO jobs VALUES(10,"Software Enginner","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",3);
INSERT INTO jobs VALUES(11,"Programmer","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",3);
INSERT INTO jobs VALUES(12,"HR","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",3);
INSERT INTO jobs VALUES(13,"Software Enginner","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",4);
INSERT INTO jobs VALUES(14,"Programmer","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",4);
INSERT INTO jobs VALUES(15,"HR","AAAAAAAAAAAAAAAAAAAAAAAAAAAA",4);

INSERT INTO applications VALUES(1,1,1);
INSERT INTO applications VALUES(2,2,1);
INSERT INTO applications VALUES(3,3,2);
INSERT INTO applications VALUES(4,4,2);
INSERT INTO applications VALUES(5,14,2);
INSERT INTO applications VALUES(6,13,1);
INSERT INTO applications VALUES(7,9,1);
INSERT INTO applications VALUES(8,3,2);
INSERT INTO applications VALUES(9,3,3);
INSERT INTO applications VALUES(10,4,2);
INSERT INTO applications VALUES(11,8,2);
INSERT INTO applications VALUES(12,9,1);
